apiVersion: "v1"
kind: "Service"
metadata:
  name: "{{ template "common.fullname" . }}"
  labels:
{{ include "common.labels" . | indent 4 }}
spec:
  type: "NodePort"

  ports:
    - port: {{ .Values.deployment.port }}
      nodePort: {{ .Values.service.nodePort }}

  selector:
{{ include "common.labels" . | indent 4 }}
